info:
    theme_name: 'Baboon Configuration Theme'
    update_zip_uri: 'https://github.com/behram/BaboonConfigurationTheme/archive/master.zip'
    update_git_uri: 'git@github.com:behram/BaboonConfigurationTheme.git'

render_files:
    - index.html
    - css/style.css
    - js/site.js

assets:
    text_text:
        type: text
        max: 400
        min: 100
        default: |
            The English Benedictine Reform in the late tenth century was the most important religious and intellectual movement in the later Anglo-Saxon period. The reformers sought to replace married secular clergy in monasteries with celibate contemplative monks who followed the Rule of Saint Benedict. The court of Æthelstan (924–39), the first king of the whole of England, began a cosmopolitan trend; future reformers such as Æthelwold of Winchester, Oswald of Worcester, and Dunstan, Archbishop of Canterbury, learned from Continental exponents of Benedictine monasticism. The reformers had close relations with the crown, furthering its interests and depending on its support, especially under King Edgar (959–75). Influential artistic workshops established by Æthelwold reached a high standard of craftsmanship in manuscript illustration, sculpture and gold and silver, and his monasteries produced scholarship and competent prose and poetry in the elaborate hermeneutic style of Latin. His Winchester school helped create the standard vernacular
    text_string:
        type: string
        max: 50
        min: 10
        default: Hello i am default
    text_markdown:
        type: markdown
        multiple: true
        max: 1000
        min: 10
    text_richtext:
        type: richtext
    image_logo:
        type: image
        width: 100
        height: 200
    file_all_type:
        type: file
        mime_types: "*"
    file_doc_type:
        type: file
        mime_types:
            - application/atom+xml
            - application/pdf
    birth_day:
        type: datetime
    select_name:
        type: choices
        choices:
          - Kalem
          - Selam
          - Kazim
          - Behram
    email:
        type: email
    font_color:
        type: color
        default: red
